### ISSUE TITLE
vertical metrics produce clipping in Windows

### ISSUE THREAD

**Issue by m4rc1e** [itfoundry/Poppins#11]
The yMin yMax is not equal the font's bbox

Currently we have:
```
winAscent: 1100
winDescent: 400
```
It should be:
```
winAscent: 1135
winDescent: 627
```

The ideal vertical metrics for this font are:
```
typoAscender = 1100
typoDescender = -400
typoLineGap = 100
winAscent = 1135
winDescent = 627
hheaAscender = 1050
hheaDescender = -350
```

Enable fsSelection bit 7 (Use_Typo_Metrics) as well.

These values will retain the visual appearance of the old font and avoid clipping. We have a [guide](https://github.com/m4rc1e/gf-docs/blob/verticalmetrics/VerticalMetrics.md) in the works

**Comment by lianghai** [comment]
Closed in https://github.com/itfoundry/Poppins/commit/4588263c7f65c012b513c242b5d05d41307554fe

I've looked into the issue and —

- For a Devanagari font, marks are dynamically positioned on bases so frequently that bbox is not quite useful anymore for determining potential clipping cases.

- Therefore there isn't much a difference between the marginal glyphs by default clipped by `winAscent`/`winDescent` (dvmvRR, dvmvL, dvmvLL, dvNG_R, dvTT_R, dvTTH_R, dvDD_R, dvDDH_R, dvD_R, dvL_R, dvH_R — in the case of this font family) and the dynamically positioned marks that fall out of the `winAscent`/`winDescent` boundary.

- Therefore I usually set `winAscent`/`winDescent` to values that only ensure that the marginal glyphs are still more or less recognizable and certain glyphs slightly compromised (dvCandrabindu, dvmEcandra_Anusvara, dvmOcandra_Anusvara — is frequently used so it's clipped), in order to have reasonable `winAscent`/`winDescent` values.

- Now from your recommendation I see — good, `winAscent` and `winDescent` are not required to match the other two groups of values anymore as long as fsSelection bit 7 is on (already on in 3.000).

- Then, okay, I can use the bbox values for `winAscent` and `winDescent` now and investigate if I need to set them larger to ensure all dynamically positioned marks are not clipped either.

- Your recommended `typoAscender`/`typoDescender`/`typoLineGap` values don't make sense to me because they're neither matching `hheaAscender`/`hheaDescender`/`hheaLineGap` nor having a zeroed `typoLineGap`. So I kept them untouched for now (and possibly revise later because the current set of values came from a project for another client and the original considerations are not helpful anymore):

```
table hhea {
  Ascender 1050;
  Descender -350;
  LineGap 100;
} hhea;

table OS/2 {
  TypoAscender 1050;
  TypoDescender -350;
  TypoLineGap 100;
  winAscent 1135;
  winDescent 627;
} OS/2;
```

**Comment by m4rc1e** [comment]
@lianghai Apologies, I overlooked the GPOS aspect.

>Your recommended typoAscender/typoDescender/typoLineGap values don't make sense to me because they're neither matching hheaAscender/hheaDescender/hheaLineGap nor having a zeroed typoLineGap. 

When you enable fsSelection bit 7, Win applications will use typo instead of the Win values. The typo values are just the old win values  :-)

**Comment by lianghai** [comment]
@m4rc1e 

> When you enable fsSelection bit 7, Win applications will use typo instead of the Win values. The typo values are just the old win values :-)

Oh… I see. But this project actually always has fsSelection bit 7 on (just checked the files from both older commits and https://fonts.google.com/specimen/Poppins) — seems we don't need to apply old `win` values to `typo` to maintain vertical metrics.

(Also, if we do use the old `win` values for `typo` while leaving the non-zero `typoLineGap` unchanged, the line height on Windows will be 160% (= 1100 + 400 + 100) while on Mac 150% (= 1050 + 350 + 100)… Note the old `win` values were set in the way of `winAscent + winDescent = typoAscender + abs(typoDescender) + typoLineGap`.)

**Comment by m4rc1e** [comment]
@lianghai 

> Oh… I see. But this project actually always has fsSelection bit 7 on 

Ahh, Apologies. Ignore my suggestion on updating the typo metrics then :-). hhea and typo should be the same as the old then..

Since the fonts already have Typo_Metrics enabled, what would happen if the win values took into account the mark positioning? so instead of setting them to the bbox,  what if they were set to include an above and below mark?

**Comment by lianghai** [comment]
@m4rc1e 

> Since the fonts already have Typo_Metrics enabled, what would happen if the win values took into account the mark positioning? so instead of setting them to the bbox, what if they were set to include an above and below mark?

I need to spend some time composing a list of typical `base mark*` sequences for calculating required `win` values. The tricky part here is finding a good threshold of ignoring those marginal and crazy cases of mark-to-mark positioning while still covering the needed ones…

Thank you for bringing this issue up. I did expect to see a recommendation that recognizes `fsSelection` bit 7's ability of decoupling `win` values from line height metrics (which is why I turned on `fsSelection` bit 7 in the first place), now we can finally get rid of `win` values' restriction on setting line height metrics.
